const data = {
  products: [
    {
      name: "Nike Canvas",
      slug: "Nike-Canvas",
      category: "shirt",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shoe",
    },
    {
      name: "Shoe no 2",
      slug: "Shoe-no-2",
      category: "shirt",
      image: "./images/p2.png",
      price: 3000,
      countInStock: 10,
      brand: "Addidas",
      rating: 2.5,
      numReviews: 70,
      description: "high quality shoe",
    },
    {
      name: "Nike Canvas",
      slug: "Nike-Canvas",
      category: "shirt",
      image: "./images/p3.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shoe",
    },
    {
      name: "Shoe no 2",
      slug: "Shoe-no-2",
      category: "shirt",
      image: "./images/p4.png",
      price: 3000,
      countInStock: 10,
      brand: "Addidas",
      rating: 2.5,
      numReviews: 70,
      description: "high quality shoe",
    },
  ],
};

export default data;
